import os
import re

SKILLS_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
README_PATH = os.path.join(SKILLS_DIR, "README.md")

def get_skill_info(skill_path):
    skill_file = os.path.join(skill_path, "SKILL.md")
    if not os.path.exists(skill_file):
        return None
    
    with open(skill_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Parse frontmatter
    name_match = re.search(r'name:\s*["\']?([^"\']+)["\']?', content)
    desc_match = re.search(r'description:\s*["\']?([^"\']+)["\']?', content)
    
    if not name_match:
        return None
        
    return {
        "name": name_match.group(1),
        "description": desc_match.group(1) if desc_match else "No description provided."
    }

def update_readme():
    skills = []
    for item in os.listdir(SKILLS_DIR):
        item_path = os.path.join(SKILLS_DIR, item)
        if os.path.isdir(item_path) and not item.startswith('.'):
            info = get_skill_info(item_path)
            if info:
                skills.append(info)
    
    skills.sort(key=lambda x: x['name'])
    
    content = "# Available Skills\n\n"
    content += "| Name | Description |\n"
    content += "|------|-------------|\n"
    
    for skill in skills:
        # Escape pipes in description to avoid breaking table
        desc = skill['description'].replace('|', '\|')
        content += f"| **{skill['name']}** | {desc} |\n"
    
    content += "\n\n_Auto-generated by skill-creator_"
    
    with open(README_PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Successfully updated {README_PATH} with {len(skills)} skills.")

if __name__ == "__main__":
    update_readme()
